#!/bin/bash
#
# analyze-codebase.sh — Quick codebase health check
#
# Usage: ./analyze-codebase.sh [directory]
# Default directory: packages/
#
# Outputs markdown summary of:
#   - Large files
#   - TODO/FIXME comments
#   - Test coverage estimation
#   - Pattern checks
#

set -e

SEARCH_DIR="${1:-packages}"

echo "# Codebase Analysis Report"
echo ""
echo "**Generated:** $(date -Iseconds)"
echo "**Directory:** $SEARCH_DIR"
echo ""

# ============================================================================
# Large Files
# ============================================================================
echo "## Large Files (>300 lines)"
echo ""
echo "| Lines | File |"
echo "|-------|------|"

find "$SEARCH_DIR" -name "*.ts" -o -name "*.tsx" 2>/dev/null | while read -r file; do
  lines=$(wc -l < "$file" | tr -d ' ')
  if [ "$lines" -gt 300 ]; then
    echo "| $lines | \`$file\` |"
  fi
done | sort -t'|' -k2 -rn | head -20

echo ""

# ============================================================================
# TODO/FIXME Comments
# ============================================================================
echo "## TODO/FIXME Comments"
echo ""

TODO_COUNT=$(grep -rn "TODO\|FIXME\|HACK\|XXX" "$SEARCH_DIR" --include="*.ts" --include="*.tsx" 2>/dev/null | wc -l | tr -d ' ')
echo "**Total:** $TODO_COUNT"
echo ""

if [ "$TODO_COUNT" -gt 0 ]; then
  echo "### Recent TODOs"
  echo ""
  echo '```'
  grep -rn "TODO\|FIXME" "$SEARCH_DIR" --include="*.ts" --include="*.tsx" 2>/dev/null | head -10
  echo '```'
  echo ""
fi

# ============================================================================
# Test Coverage Estimation
# ============================================================================
echo "## Test Coverage Estimation"
echo ""

TOTAL_FILES=$(find "$SEARCH_DIR" -name "*.ts" ! -name "*.test.ts" ! -name "*.spec.ts" ! -name "*.d.ts" 2>/dev/null | wc -l | tr -d ' ')
TEST_FILES=$(find "$SEARCH_DIR" -name "*.test.ts" -o -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')

echo "| Metric | Count |"
echo "|--------|-------|"
echo "| Source files | $TOTAL_FILES |"
echo "| Test files | $TEST_FILES |"

if [ "$TOTAL_FILES" -gt 0 ]; then
  RATIO=$(echo "scale=2; $TEST_FILES * 100 / $TOTAL_FILES" | bc)
  echo "| Test-to-source ratio | ${RATIO}% |"
fi

echo ""

# ============================================================================
# Files Without Tests
# ============================================================================
echo "## Potential Missing Tests"
echo ""
echo "_Source files without corresponding test files (sampling first 10):_"
echo ""

find "$SEARCH_DIR" -name "*.ts" ! -name "*.test.ts" ! -name "*.spec.ts" ! -name "*.d.ts" ! -name "index.ts" 2>/dev/null | head -20 | while read -r src; do
  base=$(basename "$src" .ts)
  dir=$(dirname "$src")
  
  # Check for test file in same directory
  if [ ! -f "$dir/$base.test.ts" ] && [ ! -f "$dir/$base.spec.ts" ]; then
    # Check if it's a significant file (not just types/constants)
    lines=$(wc -l < "$src" | tr -d ' ')
    if [ "$lines" -gt 50 ]; then
      echo "- \`$src\` ($lines lines)"
    fi
  fi
done | head -10

echo ""

# ============================================================================
# Duplicate Patterns
# ============================================================================
echo "## Pattern Analysis"
echo ""

echo "### Capability Files"
CAP_COUNT=$(find "$SEARCH_DIR" -name "*.capability.ts" 2>/dev/null | wc -l | tr -d ' ')
echo "- **Capability files:** $CAP_COUNT"

echo ""
echo "### Common Imports"
echo ""
echo "Most frequently imported modules:"
echo ""
echo '```'
grep -rh "from '" "$SEARCH_DIR" --include="*.ts" 2>/dev/null | \
  sed "s/.*from '\([^']*\)'.*/\1/" | \
  sort | uniq -c | sort -rn | head -10
echo '```'

echo ""

# ============================================================================
# Recommendations
# ============================================================================
echo "## Quick Recommendations"
echo ""

if [ "$TODO_COUNT" -gt 20 ]; then
  echo "- ⚠️ High TODO count ($TODO_COUNT). Consider triaging and addressing."
fi

if [ "$TEST_FILES" -lt "$((TOTAL_FILES / 2))" ]; then
  echo "- ⚠️ Test coverage appears low. Consider adding tests for critical paths."
fi

LARGE_COUNT=$(find "$SEARCH_DIR" -name "*.ts" 2>/dev/null | while read -r f; do
  lines=$(wc -l < "$f" | tr -d ' ')
  [ "$lines" -gt 300 ] && echo "$f"
done | wc -l | tr -d ' ')

if [ "$LARGE_COUNT" -gt 5 ]; then
  echo "- ⚠️ Several large files ($LARGE_COUNT > 300 lines). Consider splitting."
fi

echo ""
echo "---"
echo "_Generated by analyze-codebase.sh from retrospective skill_"
