#!/usr/bin/env bash
# score-dev.sh — run the local dev-loop scorer. Deterministic wrapper.
# Called every cycle, no round trip, no eval-repo involvement.
# The agent (or a human) runs this directly; no judgment required.
#
# Usage: ./score-dev.sh
# Output: JSON on stdout — {"score": <float>, "ci_low": <float>,
#                             "ci_high": <float>, "void": <bool>}

set -euo pipefail

# harness/score.sh is generated by Fable in design mode (Phase 5). This
# wrapper's only job is a consistent, agent-parseable output contract and
# running lint.sh first — replicate/bootstrap as needed inside score.sh
# itself per SKILL.md Phase 5.
if [ ! -x harness/score.sh ]; then
  echo '{"error": "harness/score.sh not found — run design mode first"}' >&2
  exit 1
fi

harness/lint.sh . || { echo '{"score": null, "void": true}'; exit 0; }
harness/score.sh
